[build]
  command = "npm run build"
  publish = "out"

[[redirects]]
  from = "/playground/*"
  to = "https://playgroundcv.netlify.app/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
